/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/sHgz5KRk8Zk
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { AlertTitle, AlertDescription, Alert } from "@/components/ui/alert";
interface appointmentProps {
  type: string;
}
export function Appointments({ type }: appointmentProps) {
  let text: string = type;
  let textUpper = text.charAt(0);
  textUpper = textUpper.toUpperCase() + text.slice(1);

  return (
    <div className="flex min-h-[100dvh] flex-col items-center justify-center bg-gray-100 px-4 dark:bg-gray-950">
      <div className="mx-auto w-full max-w-4xl space-y-6">
        <div className="text-center">
          <div className="flex flex-col items-center justify-between">
            <Link
              id={text}
              className="flex items-center gap-2 text-lg font-semibold"
              href="/home">
              <ArrowLeftIcon className="h-5 w-5" />
              <span>Back</span>
            </Link>
            <h1 className="text-3xl font-bold tracking-tight mt-4">
              {textUpper}'s Interface
            </h1>
          </div>
          <p className="mt-2 text-gray-500 dark:text-gray-400">
            Manage your {text}'s appointments and patients.
          </p>
        </div>
        <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
          <Card>
            <CardHeader>
              <CardTitle>Appointment Actions</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <Button className="w-full" size="lg" variant="outline">
                  <Link href="apmtform">Request Appointment</Link>
                </Button>
                <Button className="w-full" size="lg" variant="outline">
                  Cancel Appointment
                </Button>
                <Button className="w-full" size="lg" variant="outline">
                  Confirm Appointment
                  <CheckIcon className="ml-2 h-4 w-4" />
                </Button>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Appointments for Today</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <p className="text-center text-gray-500 dark:text-gray-400">
                  No appointments for today.
                </p>
              </div>
            </CardContent>
          </Card>
          <div className="col-span-1 md:col-span-2 flex items-center justify-center">
            <Alert variant="info">
              <BadgeAlertIcon className="h-5 w-5 mr-2" />
              <AlertTitle>Appointment Confirmation</AlertTitle>
              <AlertDescription>
                A new patient is about to arrive for their appointment.
              </AlertDescription>
              <Button
                className="mt-3 bg-gray-900 text-gray-50 hover:bg-gray-900/90 focus-visible:ring-gray-950 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                size="lg"
                variant="outline">
                Confirm Appointment
                <CheckIcon className="ml-2 h-4 w-4" />
              </Button>
            </Alert>
          </div>
        </div>
      </div>
    </div>
  );
}

function ArrowLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m12 19-7-7 7-7" />
      <path d="M19 12H5" />
    </svg>
  );
}

function BadgeAlertIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z" />
      <line x1="12" x2="12" y1="8" y2="12" />
      <line x1="12" x2="12.01" y1="16" y2="16" />
    </svg>
  );
}

function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M20 6 9 17l-5-5" />
    </svg>
  );
}
